//! Shared real-Factorio blueprint-string fixtures for tests across crates.
//!
//! These blueprint strings were generated by encoding known JSON payloads
//! through the standard Factorio pipeline (JSON -> zlib -> base64 -> prepend
//! '0'). They use realistic entity configurations matching real gameplay.
//!
//! Kept in one place (rather than copy-pasted per crate) so any downstream
//! crate's tests can reference `factorio_blueprint::fixtures::*` — the blueprint
//! codec's own integration tests, the grid crate's import tests, and the grid
//! renderer's unit tests all pull from here.

/// Minimal blueprint: a single transport belt facing east.
pub const SINGLE_BELT: &str = concat!(
    "0eNptzcEKgzAMgOF3ybkbKrZiX2WMUTWMgKbSVplI332tveywU0nC9/eEYd5wdcQB",
    "9AkUcAH9sxOAHCgQetCPswzHi7dlQAe6FsBmwSSCM+xX68JtwDmz1frELOfqB3R1lw",
    "KO640CJnI4lmsTnwJotFw+8PRmM2f0P5ww8YSpWGe4o/NXRqqmb/tetlWnVNfE+AWu",
    "hUgS",
);

/// Assembler with inserters and belts, tests recipe & direction fields.
pub const ASSEMBLER_SETUP: &str = concat!(
    "0eNqNkcFqwzAMhl9l6GxD6yYpyW3P0OMow0lFKrCVYDvrSsi7T1kgDJptvRgs8X2/",
    "kEao3YB9IE5QjUAJPVQ/agqcrdFJ7TVG9LXD8HLCNPTSQU6UCCNUb+Pyub/z4GsMUO",
    "0VsPUonF044lZ721yJURuB+y4K3PGc+gnVTsFd3klBwIb6GaTQsW7RBn27ooyg4ELSX",
    "CAzqYdMs2YSRwxJag852qxB/9gOT9g2ZcWGLFtlKViOfReSlrWmjQEPW85sw5k/7fx",
    "FeVZATcfL/SK1bN0M/HU3URBfUJz7Gf/AEL9leWHKrCzzbHcsiqOZpi/Cqcff",
);

/// Underground belt pair with "type": "input"/"output".
pub const UNDERGROUND_BELTS: &str = concat!(
    "0eNqVkVGKwjAQQO8y31G021aaq4gsbR1koJ2EZCKW0rubWBBBw65fQxLeeySZoRsCWk",
    "csoGcgwRH0y54CZCEh9KCP87qYfjmMHTrQewXcjhiJwGd0F2fi3HQ4JNAaH0HDyXsD",
    "vdtWCqbHXBScyWG/nhYKZLJJQmyDwKLeOsUXnfLvjgmSCf08Q+Ja9tY4yWQ2+ft88J",
    "b/9lZ57UkB9YbXn/B04XZIUO5lIk5xLzr3Cb2i8w9RVRdN2TRVuTvU9aFYljv3gKqg",
);

/// Blueprint with stone-path, concrete, and refined-concrete tiles.
pub const TILES_BLUEPRINT: &str = concat!(
    "0eNqVkcFOwzAQRH8F7dlBTWhSxbf+AzdUISdZYKVkHdluRRX531nXHKgCoj1ZXs+8sT",
    "0LdOMRZ0ccQC9AASfQP2YKRtPhKLNnGnF42Ds0MkQOFAg96Jclb86vfJw6dKBLBWwm",
    "FEtwhv1sXSgEkViz9WKznKI+QW8eawXnyxoVDOSwz6dVPCgIEpgDvnE+WMZiNuHjF1",
    "QGxahukpf3yTO9vI9+Je8t9w4DrsXV+ir/ia/IDt+IcSj+Nj2tE241SZI0QSLLTXh6",
    "ZzMmyfobpELiAdP7k+mEzl9wdVO127att5td0+yqGL8AykHMWA==",
);

/// Blueprint book with 3 sub-blueprints: a belt, a fast belt, and underground belts.
pub const BLUEPRINT_BOOK: &str = concat!(
    "0eNqdk81ugzAQhF8l2rNTBQuI4JhnaE9VhUzYRlbBRv6JiiLevWuoQqTQBnJCePab8S",
    "ziAmXtsTVSuaLU+gvyC0iHDeSTsB0EBrUosSbhFa3bHMaz65CF/J1QVeE35LsbYc7x",
    "xuyAtdtEdIDKSSdx9BleukL5pkQDecRAiQZp3BmhbKsNXYpAwlptCdMqxITkl4RBNzx",
    "7BpU0eBxV3n8wkEetxgArT0rUAZo3Jvi3SxTAMxo72CQpz+IsS+LdPk33vO/ZtXS0s",
    "jRfXPpTWLd9unn8oPmc+xP1+fL6b0SYk9FeVYt34Cdm9adn4Lo2mEjV+lDuLoevyIk",
    "f52jvhqD/F38XtXjrJAoKPWMx/XB/T/8Ar5VIQQ==",
);

/// Complex blueprint with circuit connections, combinators, modules, and control_behavior.
pub const COMPLEX_CIRCUIT: &str = concat!(
    "0eNqtVNuK2zAQ/ZWi19oldpws8UOh9BP6uAQj25NkQDdkKW0I/veOpF0nWyfLpq0NQr",
    "c5OnN0NGfWCg/GonKsPjN0IFl9NZcxwVsQNPcdbefRffoBzhuaB+XQIQysfj6nwalR",
    "XrZgWV1kTHEJFMUtuoMEh13eadmi4k5bijZ6oGitwqG/WL3I2InaL6sxYz1a6NJamb",
    "FOK2e1aFo48CNSLAVcQBta7iPQEBZ2aAfXDLhXXISxO5lA4ojWeZqZWKUd+TdGxw0Q",
    "MALQ4HhQgchrA5YnCuwzhWnvjH8MmL5spks5beyhwx7sB0QpPyjKC+J/UORKisUiDK",
    "XhNlKs2de/UyOgmBNx88o1O6tlg4owWO2sh5tSLSeUVzrvakUqPWShHQoHNpn30UT8",
    "i0tQ9UBHF4H9DCO+pAkArVa5EdzBFURVThjluL0lQnVhILkQueDS3M89OeVWtl16ux",
    "dv/Ls15sagZT8AnSF0EDbd7Dyn1aU2DAPIVqDa55J3B1SQL+fZ5ct0sQRPl4qRIwi6X",
    "pI0VJWUGsUFxaPnBwPQ51L3XkBekoq3aKwnGhJ69DJPmIRotIA5jeqNwUgHlRwWTyx",
    "CY6G/roXYR5O8Sh+H4zZjewug/ty4DPcfVn+Sc4Mrn4uspL/YZtSr6C+pF2aWsUdtt",
    "qYeRWAXSbzx8bvFd7zn3Pulabw2asaO9HKiMqt1uak2m1W1eFqvn8px/A0lpiJv",
);
