//! Integration tests with real Factorio blueprint strings.
//!
//! Validates that decode -> encode -> decode round-trips preserve all data,
//! using both struct equality and JSON value equality.

use factorio_blueprint::{decode, decode_to_json, encode};

// -- Helpers ---------------------------------------------------------------

/// Decode -> encode -> decode again, assert struct equality.
fn assert_roundtrip(s: &str) {
    let first = decode(s).unwrap_or_else(|e| panic!("first decode failed: {e}"));
    let encoded = encode(&first).unwrap_or_else(|e| panic!("encode failed: {e}"));
    let second = decode(&encoded).unwrap_or_else(|e| panic!("second decode failed: {e}"));
    assert_eq!(first, second, "struct mismatch after round-trip");
}

/// Decode original to JSON, then decode -> encode -> decode to JSON.
/// Parse both as serde_json::Value, normalize numbers, and assert equality.
///
/// Number normalization is necessary because Factorio JSON uses integers for
/// whole-number positions (e.g. `"x": 0`) but our Position type uses f64,
/// so re-serialization produces `"x": 0.0`. Both are semantically identical.
fn assert_json_equivalent(s: &str) {
    let original_json = decode_to_json(s).unwrap_or_else(|e| panic!("decode_to_json failed: {e}"));
    let original_value: serde_json::Value =
        serde_json::from_str(&original_json).expect("original JSON parse failed");

    let data = decode(s).unwrap_or_else(|e| panic!("decode failed: {e}"));
    let re_encoded = encode(&data).unwrap_or_else(|e| panic!("encode failed: {e}"));
    let roundtrip_json =
        decode_to_json(&re_encoded).unwrap_or_else(|e| panic!("decode_to_json roundtrip failed: {e}"));
    let roundtrip_value: serde_json::Value =
        serde_json::from_str(&roundtrip_json).expect("roundtrip JSON parse failed");

    assert_eq!(
        normalize_numbers(&original_value),
        normalize_numbers(&roundtrip_value),
        "JSON mismatch after round-trip"
    );
}

/// Recursively normalize all JSON numbers to f64 so that `0` and `0.0`
/// compare as equal (they represent the same value in Factorio data).
fn normalize_numbers(value: &serde_json::Value) -> serde_json::Value {
    match value {
        serde_json::Value::Number(n) => {
            let f = n.as_f64().unwrap_or(0.0);
            serde_json::Value::Number(
                serde_json::Number::from_f64(f).unwrap_or_else(|| serde_json::Number::from(0)),
            )
        }
        serde_json::Value::Array(arr) => {
            serde_json::Value::Array(arr.iter().map(normalize_numbers).collect())
        }
        serde_json::Value::Object(map) => {
            serde_json::Value::Object(map.iter().map(|(k, v)| (k.clone(), normalize_numbers(v))).collect())
        }
        other => other.clone(),
    }
}

// -- Test blueprint strings ------------------------------------------------
//
// These blueprint strings were generated by encoding known JSON payloads
// through the standard Factorio pipeline (JSON -> zlib -> base64 -> prepend '0').
// They use realistic entity configurations matching real Factorio gameplay.

/// Minimal blueprint: a single transport belt facing east.
const SINGLE_BELT: &str = concat!(
    "0eNptzcEKgzAMgOF3ybkbKrZiX2WMUTWMgKbSVplI332tveywU0nC9/eEYd5wdcQB",
    "9AkUcAH9sxOAHCgQetCPswzHi7dlQAe6FsBmwSSCM+xX68JtwDmz1frELOfqB3R1lw",
    "KO640CJnI4lmsTnwJotFw+8PRmM2f0P5ww8YSpWGe4o/NXRqqmb/tetlWnVNfE+AWu",
    "hUgS",
);

/// Assembler with inserters and belts, tests recipe & direction fields.
const ASSEMBLER_SETUP: &str = concat!(
    "0eNqNkcFqwzAMhl9l6GxD6yYpyW3P0OMow0lFKrCVYDvrSsi7T1kgDJptvRgs8X2/",
    "kEao3YB9IE5QjUAJPVQ/agqcrdFJ7TVG9LXD8HLCNPTSQU6UCCNUb+Pyub/z4GsMUO",
    "0VsPUonF044lZ721yJURuB+y4K3PGc+gnVTsFd3klBwIb6GaTQsW7RBn27ooyg4ELSX",
    "CAzqYdMs2YSRwxJag852qxB/9gOT9g2ZcWGLFtlKViOfReSlrWmjQEPW85sw5k/7fx",
    "FeVZATcfL/SK1bN0M/HU3URBfUJz7Gf/AEL9leWHKrCzzbHcsiqOZpi/Cqcff",
);

/// Underground belt pair with "type": "input"/"output".
const UNDERGROUND_BELTS: &str = concat!(
    "0eNqVkVGKwjAQQO8y31G021aaq4gsbR1koJ2EZCKW0rubWBBBw65fQxLeeySZoRsCWk",
    "csoGcgwRH0y54CZCEh9KCP87qYfjmMHTrQewXcjhiJwGd0F2fi3HQ4JNAaH0HDyXsD",
    "vdtWCqbHXBScyWG/nhYKZLJJQmyDwKLeOsUXnfLvjgmSCf08Q+Ja9tY4yWQ2+ft88J",
    "b/9lZ57UkB9YbXn/B04XZIUO5lIk5xLzr3Cb2i8w9RVRdN2TRVuTvU9aFYljv3gKqg",
);

/// Blueprint with stone-path, concrete, and refined-concrete tiles.
const TILES_BLUEPRINT: &str = concat!(
    "0eNqVkcFOwzAQRH8F7dlBTWhSxbf+AzdUISdZYKVkHdluRRX531nXHKgCoj1ZXs+8sT",
    "0LdOMRZ0ccQC9AASfQP2YKRtPhKLNnGnF42Ds0MkQOFAg96Jclb86vfJw6dKBLBWwm",
    "FEtwhv1sXSgEkViz9WKznKI+QW8eawXnyxoVDOSwz6dVPCgIEpgDvnE+WMZiNuHjF1",
    "QGxahukpf3yTO9vI9+Je8t9w4DrsXV+ir/ia/IDt+IcSj+Nj2tE241SZI0QSLLTXh6",
    "ZzMmyfobpELiAdP7k+mEzl9wdVO127att5td0+yqGL8AykHMWA==",
);

/// Blueprint book with 3 sub-blueprints: a belt, a fast belt, and underground belts.
const BLUEPRINT_BOOK: &str = concat!(
    "0eNqdk81ugzAQhF8l2rNTBQuI4JhnaE9VhUzYRlbBRv6JiiLevWuoQqTQBnJCePab8S",
    "ziAmXtsTVSuaLU+gvyC0iHDeSTsB0EBrUosSbhFa3bHMaz65CF/J1QVeE35LsbYc7x",
    "xuyAtdtEdIDKSSdx9BleukL5pkQDecRAiQZp3BmhbKsNXYpAwlptCdMqxITkl4RBNzx",
    "7BpU0eBxV3n8wkEetxgArT0rUAZo3Jvi3SxTAMxo72CQpz+IsS+LdPk33vO/ZtXS0s",
    "jRfXPpTWLd9unn8oPmc+xP1+fL6b0SYk9FeVYt34Cdm9adn4Lo2mEjV+lDuLoevyIk",
    "f52jvhqD/F38XtXjrJAoKPWMx/XB/T/8Ar5VIQQ==",
);

/// Complex blueprint with circuit connections, combinators, modules, and control_behavior.
const COMPLEX_CIRCUIT: &str = concat!(
    "0eNqtVNuK2zAQ/ZWi19oldpws8UOh9BP6uAQj25NkQDdkKW0I/veOpF0nWyfLpq0NQr",
    "c5OnN0NGfWCg/GonKsPjN0IFl9NZcxwVsQNPcdbefRffoBzhuaB+XQIQysfj6nwalR",
    "XrZgWV1kTHEJFMUtuoMEh13eadmi4k5bijZ6oGitwqG/WL3I2InaL6sxYz1a6NJamb",
    "FOK2e1aFo48CNSLAVcQBta7iPQEBZ2aAfXDLhXXISxO5lA4ojWeZqZWKUd+TdGxw0Q",
    "MALQ4HhQgchrA5YnCuwzhWnvjH8MmL5spks5beyhwx7sB0QpPyjKC+J/UORKisUiDK",
    "XhNlKs2de/UyOgmBNx88o1O6tlg4owWO2sh5tSLSeUVzrvakUqPWShHQoHNpn30UT8",
    "i0tQ9UBHF4H9DCO+pAkArVa5EdzBFURVThjluL0lQnVhILkQueDS3M89OeVWtl16ux",
    "dv/Ls15sagZT8AnSF0EDbd7Dyn1aU2DAPIVqDa55J3B1SQL+fZ5ct0sQRPl4qRIwi6X",
    "pI0VJWUGsUFxaPnBwPQ51L3XkBekoq3aKwnGhJ69DJPmIRotIA5jeqNwUgHlRwWTyx",
    "CY6G/roXYR5O8Sh+H4zZjewug/ty4DPcfVn+Sc4Mrn4uspL/YZtSr6C+pF2aWsUdtt",
    "qYeRWAXSbzx8bvFd7zn3Pulabw2asaO9HKiMqt1uak2m1W1eFqvn8px/A0lpiJv",
);

// -- Test cases ------------------------------------------------------------

#[test]
fn test_single_belt() {
    assert_roundtrip(SINGLE_BELT);
    assert_json_equivalent(SINGLE_BELT);

    // Verify expected structure
    let data = decode(SINGLE_BELT).unwrap();
    let bp = data.blueprint.expect("should be a blueprint");
    assert_eq!(bp.entities.len(), 1);
    assert_eq!(bp.entities[0].name, "transport-belt");
}

#[test]
fn test_assembler_setup() {
    assert_roundtrip(ASSEMBLER_SETUP);
    assert_json_equivalent(ASSEMBLER_SETUP);

    // Verify recipe and direction fields survive
    let data = decode(ASSEMBLER_SETUP).unwrap();
    let bp = data.blueprint.expect("should be a blueprint");
    let assembler = bp
        .entities
        .iter()
        .find(|e| e.name == "assembling-machine-2")
        .expect("should have an assembler");
    assert_eq!(assembler.recipe.as_deref(), Some("iron-gear-wheel"));
    assert_eq!(assembler.direction, factorio_blueprint::Direction::East);

    // Verify inserters are present with correct directions
    let inserters: Vec<_> = bp
        .entities
        .iter()
        .filter(|e| e.name == "inserter")
        .collect();
    assert_eq!(inserters.len(), 2);
}

#[test]
fn test_underground_belts() {
    assert_roundtrip(UNDERGROUND_BELTS);
    assert_json_equivalent(UNDERGROUND_BELTS);

    // Verify entity "type": "input"/"output"
    let data = decode(UNDERGROUND_BELTS).unwrap();
    let bp = data.blueprint.expect("should be a blueprint");
    let undergrounds: Vec<_> = bp
        .entities
        .iter()
        .filter(|e| e.name == "underground-belt")
        .collect();
    assert_eq!(undergrounds.len(), 2);

    let types: Vec<_> = undergrounds
        .iter()
        .map(|e| e.entity_type.as_deref().unwrap())
        .collect();
    assert!(types.contains(&"input"));
    assert!(types.contains(&"output"));
}

#[test]
fn test_blueprint_with_tiles() {
    assert_roundtrip(TILES_BLUEPRINT);
    assert_json_equivalent(TILES_BLUEPRINT);

    // Verify tiles are present
    let data = decode(TILES_BLUEPRINT).unwrap();
    let bp = data.blueprint.expect("should be a blueprint");
    assert!(!bp.tiles.is_empty(), "tiles should not be empty");
    assert_eq!(bp.tiles.len(), 8);

    let tile_names: Vec<_> = bp.tiles.iter().map(|t| t.name.as_str()).collect();
    assert!(tile_names.contains(&"stone-path"));
    assert!(tile_names.contains(&"concrete"));
    assert!(tile_names.contains(&"refined-concrete"));
}

#[test]
fn test_blueprint_book() {
    assert_roundtrip(BLUEPRINT_BOOK);
    assert_json_equivalent(BLUEPRINT_BOOK);

    // Verify it's a book with 3 blueprints
    let data = decode(BLUEPRINT_BOOK).unwrap();
    assert!(data.blueprint.is_none(), "should not be a single blueprint");
    let book = data.blueprint_book.expect("should be a blueprint book");
    assert_eq!(book.blueprints.len(), 3);
    assert_eq!(book.label.as_deref(), Some("Test Book"));
    assert_eq!(book.active_index, 0);

    // Verify individual blueprint labels
    assert_eq!(
        book.blueprints[0].blueprint.label.as_deref(),
        Some("Belt 1")
    );
    assert_eq!(
        book.blueprints[1].blueprint.label.as_deref(),
        Some("Belt 2")
    );
    assert_eq!(
        book.blueprints[2].blueprint.label.as_deref(),
        Some("Underground")
    );
}

#[test]
fn test_complex_with_circuits() {
    assert_roundtrip(COMPLEX_CIRCUIT);
    assert_json_equivalent(COMPLEX_CIRCUIT);

    // Verify circuit connections, modules, and control_behavior survive
    let data = decode(COMPLEX_CIRCUIT).unwrap();
    let bp = data.blueprint.expect("should be a blueprint");

    // Combinators should have control_behavior
    let arithmetic = bp
        .entities
        .iter()
        .find(|e| e.name == "arithmetic-combinator")
        .expect("should have arithmetic combinator");
    assert!(
        arithmetic.control_behavior.is_some(),
        "arithmetic combinator should have control_behavior"
    );

    let decider = bp
        .entities
        .iter()
        .find(|e| e.name == "decider-combinator")
        .expect("should have decider combinator");
    assert!(
        decider.control_behavior.is_some(),
        "decider combinator should have control_behavior"
    );

    // Constant combinator should have control_behavior
    let constant = bp
        .entities
        .iter()
        .find(|e| e.name == "constant-combinator")
        .expect("should have constant combinator");
    assert!(
        constant.control_behavior.is_some(),
        "constant combinator should have control_behavior"
    );

    // Assembler should have recipe and modules
    let assembler = bp
        .entities
        .iter()
        .find(|e| e.name == "assembling-machine-3")
        .expect("should have assembler");
    assert_eq!(assembler.recipe.as_deref(), Some("electronic-circuit"));
    assert!(
        assembler.items.is_some(),
        "assembler should have module items"
    );

    // Electric pole should have connections
    let pole = bp
        .entities
        .iter()
        .find(|e| e.name == "medium-electric-pole")
        .expect("should have electric pole");
    assert!(
        pole.connections.is_some(),
        "electric pole should have connections"
    );

    // Blueprint-level wires should survive
    assert!(bp.wires.is_some(), "blueprint should have wires");
}
