// Pins the dump-derived recipe registry against the defaults it must apply.
//
// `crates/solver/data/recipes.json` is generated by `dump-ingest` from a
// Factorio `--dump-data` dump. Most recipe fields are *omitted* rather than
// defaulted in that dump, and Rust's natural defaults are wrong for the most
// important one — see `enabled_aggregate_guards_against_bool_default_regression`.

use factorio_solver::recipe::{ItemKind, get, registry};

fn recipe(name: &str) -> &'static factorio_solver::recipe::Recipe {
    get(name).unwrap_or_else(|| panic!("{name} missing from the registry"))
}

#[test]
fn recipe_count_matches_2_0_77() {
    // 659 in the dump minus the 10 `parameter` placeholders.
    assert_eq!(registry().len(), 649);
}

/// The phase's highest-risk path. Of the 649 kept recipes exactly 326 are
/// research-locked and 323 are not (91 explicitly `enabled: true` + 232 with the
/// key absent, which Factorio treats as true). A regression to `bool::default()`
/// would report 558 locked and fail here loudly, rather than quietly making a
/// third of the game look unresearched.
#[test]
fn enabled_aggregate_guards_against_bool_default_regression() {
    let locked = registry().values().filter(|r| !r.enabled).count();
    assert_eq!(locked, 326);
    assert_eq!(registry().len() - locked, 323);
}

#[test]
fn absent_enabled_reads_as_available() {
    // All four omit `enabled` in the dump; all four are craftable from the start.
    for name in ["iron-plate", "copper-plate", "iron-gear-wheel", "stone-furnace"] {
        assert!(recipe(name).enabled, "{name} must not be research-locked");
    }
    // electronic-circuit declares `"enabled": false` explicitly — the case that
    // makes a `//`-style null-coalescing check the wrong tool here.
    assert!(!recipe("electronic-circuit").enabled);
}

#[test]
fn absent_category_and_energy_take_factorio_defaults() {
    // bulk-inserter omits `category`.
    assert_eq!(recipe("bulk-inserter").category, "crafting");
    // electronic-circuit omits `energy_required`.
    assert_eq!(recipe("electronic-circuit").energy_required, 0.5);
    // Declared values survive.
    assert_eq!(recipe("iron-plate").category, "smelting");
    assert_eq!(recipe("iron-plate").energy_required, 3.2);
}

/// Factorio serializes an empty Lua table as `{}`, and `biter-egg` is a real
/// recipe that is genuinely ingredient-free — not a placeholder to filter out.
#[test]
fn ingredient_free_recipes_survive_the_empty_table_shape() {
    let egg = recipe("biter-egg");
    assert!(egg.ingredients.is_empty());
    assert_eq!(egg.results.len(), 1);
    assert_eq!(egg.results[0].amount, 5.0);
    assert_eq!(egg.energy_required, 10.0);
}

#[test]
fn parameter_placeholders_are_filtered_out() {
    for i in 0..10 {
        assert!(get(&format!("parameter-{i}")).is_none());
    }
    assert!(!registry().keys().any(|k| k.starts_with("parameter-")));
}

/// Hidden recipes are kept, not filtered: Space Age's recycling recipes are
/// hidden but real, and a recycler-aware solver needs them. The flag is exposed
/// so the UI can filter its own picker.
#[test]
fn hidden_recipes_are_kept_with_the_flag() {
    assert_eq!(registry().values().filter(|r| r.hidden).count(), 319);
    assert!(registry().keys().any(|k| k.ends_with("-recycling")));
}

#[test]
fn fluid_ingredients_keep_their_kind() {
    let sulfur = recipe("sulfur");
    let fluids: Vec<_> = sulfur.ingredients.iter().filter(|i| i.kind == ItemKind::Fluid).collect();
    assert_eq!(fluids.len(), 2, "sulfur is made from water + petroleum gas");
    assert!(sulfur.ingredients.iter().all(|i| i.amount > 0.0));
}

#[test]
fn every_recipe_has_a_display_name() {
    // Locale coverage is 100% in the dump; a gap means the ingest degraded
    // silently rather than aborting.
    for (name, r) in registry() {
        assert!(r.display_name.is_some(), "{name} has no display_name");
        assert_eq!(&r.name, name, "registry key must match the recipe's own name");
    }
}

#[test]
fn a_representative_chain_resolves_end_to_end() {
    // The calculator (phase 5) walks exactly this shape.
    let gear = recipe("iron-gear-wheel");
    assert_eq!(gear.ingredients.len(), 1);
    assert_eq!(gear.ingredients[0].name, "iron-plate");
    assert_eq!(gear.ingredients[0].kind, ItemKind::Item);
    assert_eq!(gear.ingredients[0].amount, 2.0);
    assert_eq!(gear.results[0].name, "iron-gear-wheel");

    // Every ingredient of every recipe names an item, and no recipe is empty of
    // both inputs and outputs.
    for (name, r) in registry() {
        assert!(!r.results.is_empty() || r.hidden, "{name} produces nothing and is not hidden");
        assert!(r.ingredients.iter().all(|i| !i.name.is_empty()), "{name} has an unnamed ingredient");
    }
}
