// Pins the dump-derived technology registry against the facts built on it.
//
// `crates/solver/data/technologies.json` is generated by `dump-ingest` from a
// Factorio `--dump-data` dump. Two consumers rest on properties of this data
// rather than on the file itself — the availability gate's "never unlockable"
// rule and every `NotUnlocked` error's explanation — so the properties are
// asserted here, where a regenerated file that breaks one fails loudly instead
// of quietly changing what the solver refuses.

use std::collections::HashSet;

use factorio_solver::{recipe, tech};

#[test]
fn technology_count_matches_2_0_77() {
    assert_eq!(tech::registry().len(), 275);
}

/// Bonus-only technologies unlock no recipe and would look like dead weight to
/// a filter written at the ingest. They are kept because prerequisite chains
/// run straight through them: drop the 112 and the graph stops being a graph.
#[test]
fn the_bonus_only_technologies_are_kept() {
    let bonus_only = tech::registry().values().filter(|t| t.unlocks.is_empty()).count();
    assert_eq!(bonus_only, 112);
}

/// The whole reason this graph is ingested. A mid-game player asking for
/// chemical science hits four `AmbiguousRecipe` errors — `iron-plate`,
/// `copper-cable`, `iron-gear-wheel`, `pipe` — because a `casting-*` recipe
/// exists beside each assembler one. All four are behind this single
/// technology, so the refusal can name one remedy rather than four.
#[test]
fn foundry_unlocks_the_casting_recipes_the_ambiguity_turns_on() {
    for recipe_name in
        ["casting-iron", "casting-copper-cable", "casting-iron-gear-wheel", "casting-pipe"]
    {
        assert_eq!(
            tech::unlockers_for(recipe_name),
            vec!["foundry"],
            "{recipe_name} must be explained by exactly `foundry`"
        );
    }
}

/// Exactly 8 recipes are `enabled: false` with no technology unlocking them, so
/// no playthrough can ever reach them. `Availability::Everything` derives its
/// exclusion from that pair of facts rather than from a hardcoded name list —
/// this test is what lets it stay derived, by failing if a game update changes
/// the population instead of silently widening or narrowing what the default
/// offers.
#[test]
fn exactly_eight_recipes_can_never_be_unlocked() {
    let mut never: Vec<&str> = recipe::registry()
        .values()
        .filter(|r| !r.enabled && tech::unlockers_for(&r.name).is_empty())
        .map(|r| r.name.as_str())
        .collect();
    never.sort_unstable();
    assert_eq!(
        never,
        vec![
            "express-loader",
            "fast-loader",
            "heat-interface",
            "infinity-chest",
            "infinity-pipe",
            "loader",
            "pistol",
            "turbo-loader",
        ]
    );
}

/// The other half of that rule, and the one it would be easy to get wrong:
/// `enabled: false` alone does NOT mean unreachable. 326 recipes are research
/// locked and all but the eight above are unlocked by something, so a rule
/// keyed on `enabled` instead of on the graph would exclude a third of the game
/// from the default.
#[test]
fn research_locked_recipes_are_reachable_when_a_technology_unlocks_them() {
    let uranium = recipe::get("uranium-processing").expect("uranium-processing present");
    assert!(!uranium.enabled, "test premise: it is research-locked");
    assert_eq!(tech::unlockers_for("uranium-processing"), vec!["uranium-processing"]);

    let unreachable = recipe::registry()
        .values()
        .filter(|r| !r.enabled && tech::unlockers_for(&r.name).is_empty())
        .count();
    let locked = recipe::registry().values().filter(|r| !r.enabled).count();
    assert_eq!((locked, unreachable), (326, 8));
}

/// The ingest validates this on write; asserting it again on read is what
/// catches a hand-edited data file, which is the only way it could now break.
#[test]
fn every_prerequisite_names_a_technology_in_the_registry() {
    for t in tech::registry().values() {
        for prerequisite in &t.prerequisites {
            assert!(
                tech::get(prerequisite).is_some(),
                "{} lists prerequisite '{prerequisite}', which is absent",
                t.name
            );
        }
    }
}

/// The dangling-unlock drop, from the consuming side: every surviving edge
/// points at a recipe that actually exists, so `unlockers_for` can never
/// explain an item the registry has never heard of.
#[test]
fn every_unlock_names_a_recipe_in_the_registry() {
    for t in tech::registry().values() {
        for unlocked in &t.unlocks {
            assert!(
                recipe::get(unlocked).is_some(),
                "{} unlocks '{unlocked}', which is not a known recipe",
                t.name
            );
        }
    }
}

/// A recipe can have several unlockers — `iron-stick` has four — so the
/// explanation is a list, never a single name, and its order is pinned so an
/// error message does not reshuffle between runs over a HashMap.
#[test]
fn unlockers_are_sorted_and_may_number_more_than_one() {
    let sticks = tech::unlockers_for("iron-stick");
    assert!(sticks.len() > 1, "expected several unlockers, got {sticks:?}");
    let mut sorted = sticks.clone();
    sorted.sort_unstable();
    assert_eq!(sticks, sorted);
}

/// Display names come from `technology-locale.json`, which covers all 275.
#[test]
fn every_technology_carries_a_display_name() {
    let missing: Vec<&str> = tech::registry()
        .values()
        .filter(|t| t.display_name.is_none())
        .map(|t| t.name.as_str())
        .collect();
    assert!(missing.is_empty(), "technologies with no display name: {missing:?}");
    assert_eq!(tech::get("automation-3").unwrap().display_name.as_deref(), Some("Automation 3"));
}

/// Nothing is keyed twice, and the reverse index covers every edge the forward
/// one declares.
#[test]
fn the_reverse_index_covers_every_forward_edge() {
    let mut edges: HashSet<(&str, &str)> = HashSet::new();
    for t in tech::registry().values() {
        for unlocked in &t.unlocks {
            edges.insert((unlocked.as_str(), t.name.as_str()));
        }
    }
    for (recipe_name, tech_name) in edges {
        assert!(
            tech::unlockers_for(recipe_name).contains(&tech_name),
            "{tech_name} unlocks {recipe_name} but the reverse index disagrees"
        );
    }
}
