// Pins the dump-derived prototype registry against the values it must reproduce.
//
// `crates/grid/data/prototypes.json` is generated by `dump-ingest` from a
// Factorio `--dump-data` dump, not hand-written. These assertions exist so a
// change to the derivation rules cannot silently reshape the committed data:
// the first half locks in values the hand-written table already had right, and
// the second locks in the five it had wrong.
//
// Recipe assertions deliberately live in `crates/solver/tests/` instead — `grid`
// sits *below* `solver` in the crate graph, so asserting on recipes here would
// mean adding `factorio-solver` as a dev-dependency of `grid` and inverting the
// dependency direction.

use factorio_grid::prototype::{FluidConnectionType, all_names, lookup};

fn size(name: &str) -> (u32, u32) {
    let p = lookup(name).unwrap_or_else(|| panic!("{name} missing from the registry"));
    (p.tile_width, p.tile_height)
}

#[test]
fn entity_count_matches_2_0_77() {
    // flags ∋ "player-creation" && selection_box != null, on 2.0.77 + Space Age.
    // A drift here means the filter stopped matching, not that the game changed.
    assert_eq!(all_names().len(), 169);
}

/// The derivation must reproduce what the hand-written table already had right —
/// 80 of its 85 entries. These cover each family the rule has to get correct:
/// sub-tile colliders, even/odd footprints, rotated pairs, and explicit
/// tile_width/tile_height declarations that contradict the collision box.
#[test]
fn regenerated_data_preserves_known_good_sizes() {
    assert_eq!(size("transport-belt"), (1, 1));
    assert_eq!(size("inserter"), (1, 1), "0.3-wide collider still occupies a full tile");
    assert_eq!(size("assembling-machine-2"), (3, 3));
    assert_eq!(size("electric-furnace"), (3, 3));
    assert_eq!(size("chemical-plant"), (3, 3));
    assert_eq!(size("storage-tank"), (3, 3));
    assert_eq!(size("oil-refinery"), (5, 5));
    assert_eq!(size("splitter"), (2, 1));
    assert_eq!(size("pump"), (1, 2));
    assert_eq!(size("arithmetic-combinator"), (1, 2));
    // Both of these declare tile_width/tile_height that contradict their boxes:
    // trains pass through a train-stop, so its collision box is 1x1.
    assert_eq!(size("train-stop"), (2, 2));
    assert_eq!(size("offshore-pump"), (1, 1));
}

/// The five footprints the hand-written table got WRONG — every one a Space Age
/// building, i.e. exactly what someone would guess at without the game open.
/// Pinned by name so a future rule change cannot silently revert them: a wrong
/// footprint means wrong collision detection and misplaced entities on import.
#[test]
fn regenerated_data_corrects_five_wrong_footprints() {
    assert_eq!(size("big-mining-drill"), (5, 5), "was 3x3");
    assert_eq!(size("foundry"), (5, 5), "was 4x4");
    assert_eq!(size("biolab"), (5, 5), "was 4x4");
    assert_eq!(size("rocket-turret"), (3, 3), "was 2x2");
    assert_eq!(size("recycler"), (2, 4), "was 2x2");
}

#[test]
fn belt_throughput_tiers_are_unchanged() {
    let tp = |n: &str| lookup(n).unwrap().belt_throughput;
    assert_eq!(tp("transport-belt"), Some(15.0));
    assert_eq!(tp("fast-transport-belt"), Some(30.0));
    assert_eq!(tp("express-transport-belt"), Some(45.0));
    assert_eq!(tp("turbo-transport-belt"), Some(60.0));
    assert_eq!(tp("splitter"), Some(15.0));
    assert_eq!(tp("underground-belt"), Some(15.0));
    // Robots carry `.speed` too but are not belts.
    assert_eq!(tp("logistic-robot"), None);
    assert_eq!(tp("inserter"), None);
}

#[test]
fn fluid_connection_counts_match_the_game() {
    let count = |n: &str| lookup(n).unwrap().fluid_connections.len();
    assert_eq!(count("chemical-plant"), 4);
    assert_eq!(count("oil-refinery"), 5);
    assert_eq!(count("pump"), 2);
    // Corrected: the hand-written table claimed 1. The game has 4.
    assert_eq!(count("storage-tank"), 4);
    assert_eq!(count("transport-belt"), 0);
}

/// Positions are the dump's raw centre-relative `pipe_connections[].position`,
/// which is a *different* convention from the old hand-written values. Nothing
/// consumes this field yet (the generator, phase 6, is the first thing that
/// will), so the one property worth pinning is that the convention is applied
/// consistently rather than per-entity.
#[test]
fn fluid_connections_use_the_centre_relative_convention() {
    let plant = lookup("chemical-plant").unwrap();
    let inputs: Vec<_> =
        plant.fluid_connections.iter().filter(|c| c.connection_type == FluidConnectionType::Input).collect();
    let outputs: Vec<_> =
        plant.fluid_connections.iter().filter(|c| c.connection_type == FluidConnectionType::Output).collect();
    assert_eq!(inputs.len(), 2);
    assert_eq!(outputs.len(), 2);
    // Inputs on the north edge, outputs on the south, symmetric about the centre.
    assert!(inputs.iter().all(|c| c.dy == -1.0));
    assert!(outputs.iter().all(|c| c.dy == 1.0));
    assert_eq!(inputs.iter().map(|c| c.dx).sum::<f64>(), 0.0);
}

#[test]
fn dump_derived_fields_are_populated() {
    let belt = lookup("transport-belt").unwrap();
    assert_eq!(belt.display_name.as_deref(), Some("Transport belt"));
    assert_eq!(belt.icon_path.as_deref(), Some("__base__/graphics/icons/transport-belt.png"));

    let ins = lookup("inserter").unwrap();
    assert_eq!(ins.pickup_position, Some((0.0, -1.0)));
    assert_eq!(ins.insert_position, Some((0.0, 1.2)));

    // Underground span, needed by the generator's belt routing.
    assert_eq!(lookup("underground-belt").unwrap().underground_max_distance, Some(5));
    assert_eq!(lookup("turbo-underground-belt").unwrap().underground_max_distance, Some(11));
    assert_eq!(belt.underground_max_distance, None);

    // Crafting categories, needed by the calculator's machine<->recipe match.
    let asm = lookup("assembling-machine-2").unwrap();
    assert!(asm.crafting_categories.iter().any(|c| c == "crafting"));
    assert!(asm.crafting_categories.iter().any(|c| c == "crafting-with-fluid"));
    assert!(belt.crafting_categories.is_empty());
}

#[test]
fn every_prototype_has_a_display_name_and_icon() {
    // Locale and icon coverage is 100% in the dump; a gap means the ingest
    // silently degraded rather than aborting.
    for name in all_names() {
        let p = lookup(name).unwrap();
        assert!(p.display_name.is_some(), "{name} has no display_name");
        assert!(p.icon_path.is_some(), "{name} has no icon_path");
        let path = p.icon_path.as_deref().unwrap();
        assert!(path.starts_with("__"), "{name} icon path is not mod-relative: {path}");
    }
}

/// `power_kw` is *consumption* only. The hand-written table mixed production
/// into the same field for steam-engine/steam-turbine/solar-panel, which would
/// make any solver summing loads count a solar panel as a 60 kW draw. Generators
/// therefore have no `power_kw`; deriving their output is backlogged.
#[test]
fn power_kw_is_consumption_only() {
    assert_eq!(lookup("assembling-machine-2").unwrap().power_kw, Some(150.0));
    assert_eq!(lookup("foundry").unwrap().power_kw, Some(2500.0));
    assert_eq!(lookup("solar-panel").unwrap().power_kw, None);
    assert_eq!(lookup("steam-engine").unwrap().power_kw, None);
}
